MaxPlayers = 128
LogfilePath = "logs.txt"
WorldSize = 100
MinimalDistance = 60.0
EdgeDistance = 140.0
PaytimeInterval = 5

PlanetCost = 2
AsteroidCost = 2
StationCost = 2
PlanetPayout = 1
AsteroidPayout = 2
MovementCost = 1
HealAmount = 1

InitialPlayerPower = 3
InitialPlayerHealth = 3
InitialHealingPrice = 10
HealCostMultiplier = 2
StationDamage = 1
MaxHealth = 3